id: opecha:P007126
initial_creation_type: ocr
source_metadata:
  id: bdr:W23765
  title: བཀྲིས་ལྷུན་པོ་དཔལ་གྱི་བདེ་ཆེན་ཕྱོགས་ཐམས་ཅད་ལས་རྣམ་པར་རྒྱལ་བའི་གླིང་གི་དགེ་འདུན་དབུ་དམངས་དང
  volume: ''
  author: ''
