id: P007126
initial_creation_type: ocr
source_metadata:
  id: bdr:W23765
  title: བཀྲིས་ལྷུན་པོ་དཔལ་གྱི་བདེ་ཆེན་ཕྱོགས་ཐམས་ཅད་ལས་རྣམ་པར་རྒྱལ་བའི་གླིང་གི་དགེ་འདུན་དབུ་དམངས་དང
  author: ''
  volumes:
    5da1ed038c944bd991d4e4157cfcfa30:
      image_group_id: I2634
      title: ''
      volume_number: 1
      total_pages: 170
ebook_metadata:
  title: བཀྲིས་ལྷུན་པོ་དཔལ་གྱི་བདེ་ཆེན་ཕྱོགས་ཐམས་ཅད་ལས་རྣམ་པར་རྒྱལ་བའི་གླིང་གི་དགེ་འདུན་དབུ་དམངས་དང
  author: ''
  sku: P007126
  cover: cover.jpg
  layers:
  - pagination
